# Generated by Django 4.2.3 on 2023-08-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/Profile.png', upload_to='users/%Y/%m/%d', verbose_name='Фото профиля'),
        ),
    ]
